package com.example.demo;

import java.sql.Blob;

import org.springframework.beans.factory.annotation.Autowired; 
import org.springframework.stereotype.Controller; 
import org.springframework.web.bind.annotation.GetMapping; 
import org.springframework.web.bind.annotation.PostMapping; 
import org.springframework.web.bind.annotation.RequestMapping; 
import org.springframework.web.bind.annotation.RequestParam; 
import org.springframework.web.bind.annotation.ResponseBody; 
  
// This means that this  
// class is a Controller 
@Controller    
  
// This means URL's start with /geek (after Application path) 
@RequestMapping(path="/api")  
public class UserController { 
    
    // This means to get the bean called geekuserRepository 
    // Which is auto-generated by Spring, we will use it 
      // to handle the data 
    @Autowired 
    private UserRepository userRepository; 
  
    // Map ONLY POST Requests 
    @PostMapping(path="/adduser", produces = "application/json")
    public @ResponseBody User addUsers (@RequestParam String mail, @RequestParam String password, @RequestParam String role,
                                        @RequestParam Blob image) { 
        
        // @ResponseBody means the returned String 
          // is the response, not a view name 
        // @RequestParam means it is a parameter 
          // from the GET or POST request 
        
        User user = new User(); 
        user.setMail(mail); 
        user.setPassword(password);
        user.setRole(role); 
        user.setImage(image); 
        if (checkUserForAdding(user) == true) { 
          userRepository.save(user); 
          return user;
          //return "Details got Saved";
        }
        return new User();
        //else return "This email has already used";
    }
     /**
      * проверяет наличие пользователя с таким email в бд
      * @param new_user - пользователь, которого нужно проверить
      * @return true - если пользователь не найден
      */
    private boolean checkUserForAdding(User new_user) {
        Iterable <User> listOfAllusers = getAllUsers();
        for (User user : listOfAllusers) {
          if (new_user.getMail().equals(user.getMail())) return false;
        }
        return true;
    }
    
    /**
     * проверяет наличие пользователя с такими данными в бд
     * @param new_user - пользователь, которого нужно проверить
     * @return найденного пользователя или нового незаполненного пользователя
     */
    private User checkUserForEnter(User new_user) {
      Iterable <User> listOfAllusers = getAllUsers();
      for (User user : listOfAllusers) {
        if (new_user.getMail().equals(user.getMail()) && new_user.getPassword().equals(user.getPassword())) {
          return user;//return true;
        }
      }
      return new User();
      //return false;
    }
    
    /**
     * обрабатывает POST-запросы на вход в аккаунт
     * @param mail - введенная почта
     * @param password - введенный пароль
     * @return найденного пользователя или нового незаполненного пользователя
     */
    @PostMapping(path="/enter", produces = "application/json")  
    public @ResponseBody User enter(@RequestParam String mail, @RequestParam String password) { 
      User user = new User(); 
      user.setMail(mail); 
      user.setPassword(password);
      User us1 = checkUserForEnter(user);
      if (us1.getMail() == null) {  
        //return "OK";
        return new User();
      }
      return us1;
    }

    /**
     * отвечает на GET-запрос "Покажи все строки бд"
     * @return информацию, содержащуюся в бд
     */
    @GetMapping(path="/users") 
    public @ResponseBody Iterable<User> getAllUsers() { 
        // This returns a JSON or XML with the Book 
        return userRepository.findAll(); 
    } 
} 